from __future__ import annotations

import importlib.util
import json
import re
import shutil
from copy import deepcopy
from datetime import datetime
from pathlib import Path
from xml.etree import ElementTree as ET


REPO_ROOT = Path(__file__).resolve().parents[1]
GENERATOR_PATH = REPO_ROOT / "scripts" / "generate-makerspace-design.py"


def load_generator():
    spec = importlib.util.spec_from_file_location("makerspace_generator", GENERATOR_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load {GENERATOR_PATH}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def read_generated_payload(data_file: Path) -> dict:
    source = data_file.read_text(encoding="utf-8")
    match = re.search(r"export const makerspaceDesignData = (.*);\s*$", source, re.S)
    if not match:
        raise RuntimeError(f"Could not parse generated data module: {data_file}")
    return json.loads(match.group(1))


def write_generated_payload(data_file: Path, payload: dict) -> None:
    data_file.write_text(
        "/* This file is generated by scripts/update-makerspace-desktop-first-two.py. */\n"
        f"export const makerspaceDesignData = {json.dumps(payload, ensure_ascii=True, indent=2)};\n",
        encoding="utf-8",
    )


def backup_existing_outputs(gen) -> None:
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    backup_dir = REPO_ROOT / ".local-dev" / "makerspace-first-two-backups" / stamp
    backup_dir.mkdir(parents=True, exist_ok=True)
    for path in [
        gen.DATA_FILE,
        gen.BACKGROUND_DIR / "page-1-background.png",
        gen.BACKGROUND_DIR / "page-2-background.png",
        gen.TEXT_OVERLAY_DIR / "page-1-text.svg",
        gen.TEXT_OVERLAY_DIR / "page-2-text.svg",
    ]:
        if path.exists():
            shutil.copy2(path, backup_dir / path.name)
    print(f"Backed up current first-two desktop outputs to {backup_dir}")


def update_page(gen, payload: dict, page_key: str, background_name: str, text_name: str, crop: tuple[float, float, float, float]) -> None:
    root = ET.parse(gen.MASTER_SOURCE).getroot()
    gen.apply_crop(root, crop)

    # These controls are rendered as real React hotspots/buttons. Keep the SVG
    # artwork/text behind them from duplicating the interactive layer.
    gen.remove_elements_by_id(root, gen.GLOBAL_REMOVE_IDS)

    overlay_root = gen.build_text_overlay(root, [])
    overlay_path = gen.TEXT_OVERLAY_DIR / text_name
    ET.ElementTree(overlay_root).write(overlay_path, encoding="utf-8", xml_declaration=True)

    background_root = deepcopy(root)
    gen.remove_all_text(background_root)
    background_source = gen.WORK_DIR / f"{page_key}-first-two-background-source.svg"
    ET.ElementTree(background_root).write(background_source, encoding="utf-8", xml_declaration=True)
    gen.export_background(background_source, gen.BACKGROUND_DIR / background_name)

    view_box, width, height = gen.viewbox_metrics(root)
    payload["pages"][page_key] = {
        "viewBox": view_box,
        "width": width,
        "height": height,
        "background": f"/makerspace-design/backgrounds/{background_name}",
        "textOverlay": f"/makerspace-design/generated/text-overlays/{text_name}",
        "markup": gen.serialize_children(overlay_root),
    }


def main() -> None:
    gen = load_generator()
    if not gen.MASTER_SOURCE.exists():
        raise FileNotFoundError(f"Master design file not found: {gen.MASTER_SOURCE}")

    gen.BACKGROUND_DIR.mkdir(parents=True, exist_ok=True)
    gen.TEXT_OVERLAY_DIR.mkdir(parents=True, exist_ok=True)
    gen.WORK_DIR.mkdir(parents=True, exist_ok=True)

    payload = read_generated_payload(gen.DATA_FILE)
    backup_existing_outputs(gen)

    update_page(gen, payload, "home", "page-1-background.png", "page-1-text.svg", (0.0, 0.0, 508.0, 264.58337))
    update_page(gen, payload, "volunteer", "page-2-background.png", "page-2-text.svg", (0.0, 264.58337, 508.0, 264.58334))

    write_generated_payload(gen.DATA_FILE, payload)
    print("Updated desktop home and volunteer generated assets from the master SVG only.")


if __name__ == "__main__":
    main()
